---
title: "Le vote des QPV"
subtitle: "dans la métropole de Lyon"
author: "Auteur"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
    rmarkdown::html_document:
      #number_sections: true
      theme: paper
      toc: true
      toc_depth: 4
      collapsed: true
      smooth_scroll: true
      css: styles.css
      includes:
        in_header: header.html
        after_body: footer.html
---

```{r setup, include=FALSE}
# Paramètres généraux
knitr::opts_chunk$set(
	eval = TRUE,
	echo = FALSE,
	fig.align = "center",
	fig.show = "hold",
	message = FALSE,
	warning = FALSE,
	collapse = TRUE,
	out.width = "100%",
	results = "asis"
)
```

```{r logo}
# Logo Datactivist haut de page
htmltools::img(src = "https://nextcloud.datactivist.coop/s/o53wzfMNnFosQni/preview", 
               alt = 'logo', 
               style = 'position:absolute; top:0; left:0.5; padding-top:10px;') #padding=taille des espaces autour
```

```{r packages}
library(sf)
library(httr)
library(here)
library(banR)
library(tidyverse)
```


# Calcul des contours des BV

- on va utiliser ce qui existe déjà, en open data ou dans Cartelec (mais a priori Cartelec ne va pas beaucoup aider). 
- on n'a ainsi besoin de calculer les contours des BV uniquement pour les communes pas couvertes par open data ou Cartelec ET dans lesquelles il y a un QPV.

```{r communes_grand_lyon}

communes_gd_lyon <- read_csv2("https://download.data.grandlyon.com/ws/grandlyon/adr_voie_lieu.adrcomgl/all.csv?maxfeatures=100&start=1")

communes_gd_lyon_shp <- httr::GET(URLencode("https://download.data.grandlyon.com/wfs/grandlyon?SERVICE=WFS&VERSION=2.0.0&request=GetFeature&typename=adr_voie_lieu.adrcomgl&outputFormat=application/json; subtype=geojson&SRSNAME=EPSG:4171"))
communes_gd_lyon_shp <- httr::content(communes_gd_lyon_shp, as = "text")
communes_gd_lyon_shp <- st_read(communes_gd_lyon_shp, drivers = "GeoJSON", quiet = TRUE)

```

```{r open_data_2022}
bv_gd_lyon_OD_2022 <- GET(URLencode("https://download.data.grandlyon.com/wfs/grandlyon?SERVICE=WFS&VERSION=2.0.0&request=GetFeature&typename=ter_territoire.terbureauvoteperim&outputFormat=application/json; subtype=geojson&SRSNAME=EPSG:4171"))

bv_gd_lyon_OD_2022 <- content(bv_gd_lyon_OD_2022, as = "text")
bv_gd_lyon_OD_2022 <- st_read(bv_gd_lyon_OD_2022, quiet = TRUE)

# enlever les rues dont on n'a pas besoin
bv_gd_lyon_OD_2022 <- bv_gd_lyon_OD_2022 %>% 
  select(-rues)

# communes pour lesquelles on dispose des données

communes_OD_2022 <- bv_gd_lyon_OD_2022 %>% 
  as_tibble() %>% 
  distinct(insee, commune)

# attention à Lyon (commune : 69123 vs arrondissements : 69381 à 69389)
communes_OD_2022 <- communes_OD_2022 %>% 
  mutate(insee = case_when(insee %in% as.character(69381:69389) ~ "69123",
                           TRUE ~ insee)) %>% 
  distinct(insee)

```

```{r cartelec}

cartelec_2017 <- st_read(here("data", "bv_2017.gpkg"))
cartelec_2017 <- cartelec_2017 %>% st_transform(4326)
communes_cartelec_2017 <- cartelec_2017 %>% 
  filter(codedep %in% "69") %>% 
  as_tibble() %>% 
  distinct(CodeINSEE, libelle_commune)
communes_cartelec_2017 <- communes_cartelec_2017 %>% 
  mutate(CodeINSEE = case_when(CodeINSEE %in% as.character(69381:69389) ~ "69123",
                           TRUE ~ CodeINSEE))
```

```{r qpv}

qpv <- st_read(here("data", "QP_METROPOLE_LB93.shp"), quiet = TRUE)
communes_qpv <- communes_gd_lyon_shp %>% 
  st_transform(st_crs(qpv)) %>% 
  st_intersects(qpv)
communes_qpv <- communes_gd_lyon_shp %>% 
  as_tibble() %>% 
  filter(map_lgl(communes_qpv, ~ length(.) > 0))
qpv <- st_transform(qpv, 4326)
  
```


```{r a_produire}

# on produit pour toutes les communes du Grand Lyon car sinon on a un problème d'hétérogénéité à gérer

# 2022
aproduire_2022 <- communes_gd_lyon %>% # communes du grand lyon
  mutate(insee = as.character(insee)) %>% 
  anti_join(communes_OD_2022, by = "insee")  # qui ne sont pas déjà couvertes en OD

# 2017
aproduire_2017 <- communes_gd_lyon %>% # communes du grand lyon
  mutate(insee = as.character(insee)) %>% 
  anti_join(communes_cartelec_2017, by = c("insee" = "CodeINSEE"))  # qui ne sont pas déjà couvertes en OD

```

```{r import_listes_2017}
# dans le fichier original quelques guillemets trainaient, on les supprime :
# sed 's/"//g' liste\ électorale\ 2017\ Rhône.csv > liste_electorale_2017.csv
liste_2017 <- read_csv2(here("data/listes électorales", "liste_electorale_2017.csv"), col_select = c("numéro du bureau de vote", "NumeroVoie", "LibelleVoie", "Code postal", "VilleLocalite", "Code INSEE"), col_types = "cccccc")
```

```{r import_listes_2022}
# codes <- aproduire_2022 %>% magrittr::extract2("insee")

fichiers <- fs::dir_ls(here("data", "listes électorales", "listes 2022"))
# fichiers <- fichiers[str_detect(fichiers, paste0(codes, collapse = "|"))]

liste_2022 <- map_df(fichiers, 
                     ~ read_csv2(., col_select = c("code du bureau de vote", "numéro de voie", "libellé de voie", "code postal", "commune"), col_types = cols(.default = col_character())))

# le code insee n'est pas fourni par défaut... on le rajoute

source(here("functions", "match_commune.R"))

mem_match_commune <- memoise::memoise(match_commune, cache = memoise::cache_filesystem(here("cache")))

liste_2022 <- liste_2022 %>% 
  rowwise() %>% 
  mutate(code_insee = mem_match_commune(commune, "69")) %>% 
  filter(!is.na(code_insee)) %>% 
  ungroup()

write_excel_csv(liste_2022, here("data/listes électorales", "liste_2022_dep69.csv"))

```


```{r source_create_bv}
source(here("functions", "create_bv.R"))
mem_create_bv <- memoise::memoise(create_bv, cache = memoise::cache_filesystem(here("cache")))
```


```{r calcul_bv_2017}

bv_2017_produits <- aproduire_2017 %>% 
  magrittr::extract2("insee") %>% 
  map_df(~ create_bv(liste_2017, code_bv = , code_insee_commune = ., seuil = 0.6))

st_write(bv_2017_produits, here("output_data", "bv_produits_2017.gpkg"), append = FALSE)
# bv_2017_produits <- st_read(here("output_data", "bv_produits_2017.gpkg"))
```

```{r weights_2017}

m_geocode_tbl <- memoise::memoise(geocode_tbl, cache = memoise::cache_filesystem(here("cache")))

poids_2017 <- liste_2017 %>% 
  mutate(bv = as.character(`numéro du bureau de vote`)) %>% 
  mutate(adresse = paste0(NumeroVoie, " ", LibelleVoie)) %>% 
  count(adresse, `Code INSEE`) %>% 
  geocode_tbl(adresse = adresse, code_insee = `Code INSEE`)
poids_2017 <- poids_2017 %>% 
    filter(!is.na(longitude), !is.na(latitude)) %>% 
    st_as_sf(coords = c("longitude", "latitude")) %>% 
    st_set_crs(4326)

```


```{r calcul_bv_2022}

# faisons pour tout le département (les périmètres fournis en OD par la métropole sont pour certains invalides...)
bv_2022_produits <- liste_2022 %>%
  distinct(code_insee) %>% 
  magrittr::extract2("code_insee") %>% 
  map_df(~ create_bv(liste_2022, code_insee_commune = ., seuil = 0.6, code_insee = code_insee, numero_voie = `numéro de voie`, libelle_voie = `libellé de voie`, code_bv = `code du bureau de vote`))
st_write(bv_2022_produits, here("output_data", "bv_produits_2022.gpkg"))
# bv_2022_produits <- st_read(here("output_data", "bv_produits_2022.gpkg"))
```

```{r weights_2022}

poids_2022 <- liste_2022 %>% 
  mutate(bv = paste0(code_insee, str_pad(`code du bureau de vote`, 4, "left", "0"))) %>% 
  mutate(adresse = paste0(`numéro de voie`, " ", `libellé de voie`)) %>% 
  count(adresse, code_insee) %>% 
  geocode_tbl(adresse = adresse, code_insee = code_insee)
poids_2022 <- poids_2022 %>% 
    filter(!is.na(longitude), !is.na(latitude)) %>% 
    st_as_sf(coords = c("longitude", "latitude")) %>% 
    st_set_crs(4326)

```


```{r assemblage_2017}
bv_2017 <- bind_rows(
  bv_2017_produits %>% 
    mutate(code_insee = str_sub(bureau_vote_id, 1, 5)) ,
  cartelec_2017 %>% 
    filter(codedep %in% "69") %>% 
    select(code_insee = CodeINSEE, bureau_vote_id, geom)
  )

st_write(bv_2017, here("output_data", "bv_2017.gpkg"), append = FALSE)
```

```{r assemblage_2022}
bv_2022 <- bv_2022_produits %>% 
    mutate(code_insee = str_sub(bureau_vote_id, 1, 5)) %>% 
    filter(code_insee %in% communes_gd_lyon$insee) %>% 
    rename(geom = voronois)

bv_communes_2022 <- bv_2022 %>% 
    mutate(id = bureau_vote_id, 
           type = "bv")
st_write(bv_communes_2022, here("output_data", "bv_communes_2022.gpkg"), append = FALSE)
# bv_communes_2022 <- st_read(here("output_data", "bv_communes_2022.gpkg"))
```

```{r import_elections}

# présidentielles 2017 T1

# presidentielle_2017_t1_bv <- read_csv("https://www.data.gouv.fr/fr/datasets/r/f4c23dab-46ff-4799-b217-1ab29db7938b")
presidentielle_2017_t1_bv <- read_csv("https://nextcloud.datactivist.coop/s/i2Z6Cc9LZqQHm3f/download/Presidentielle_2017_Resultats_BV_T1_clean_def.csv")


# présidentielles 2017 T2

download.file("https://www.data.gouv.fr/fr/datasets/r/2e3e44de-e584-4aa2-8148-670daf5617e1", destfile = here("data", "presidentielle_2017_T2_bv.csv"))
header_P17T2 <- names(read_csv2(here("data", "presidentielle_2017_T2_bv.csv"), locale = locale(encoding = "ISO-8859-1"), n_max = 1))
n_col <- ncol(read_csv2(here("data", "presidentielle_2017_T2_bv.csv"), locale = locale(encoding = "ISO-8859-1"), skip = 1, col_names =FALSE))
nrep <- (n_col-21) / 7
presidentielle_2017_t2_bv <- read_csv2(here("data", "presidentielle_2017_T2_bv.csv"), locale = locale(encoding = "ISO-8859-1"), skip = 1, col_names = c(header_P17T2[-c(22:28)], paste0(rep(c("no_panneau", "sexe", "nom", "prenom", "voix", "voix_ins", "voix_exp"), nrep), "_", rep(seq(1:nrep), each = 7))))

presidentielle_2017_t2_bv <- presidentielle_2017_t2_bv %>% 
  mutate(CodeBV = paste0(`Code du département`, `Code de la commune`, `Code du b.vote`)) %>% 
  rename(MACRON = voix_1, `LE PEN` = voix_2) %>% 
  select(CodeBV, Inscrits, Abstentions, Votants, Blancs, Nuls, Exprimés, MACRON, `LE PEN`)

write_excel_csv(presidentielle_2017_t2_bv, here("data", "presidentielle_2017_t2_bv_clean.csv"))
# presidentielle_2017_t2_bv <- read_csv(here("data", "presidentielle_2017_t2_bv_clean.csv"))

# législatives 2017 T1

path_leg_2017_t1 <- fs::fs_path(here("data", "legislatives_2017_T1_bv.csv"))

# si besoin
# download.file("https://www.data.gouv.fr/fr/datasets/r/80cb1309-9147-4bae-b6e2-79877d549b50", destfile = path_leg_2017_t1)

header_L17T1 <- names(read_csv2(path_leg_2017_t1, locale = locale(encoding = "ISO-8859-1"), n_max = 1))

# n_col <- system2(paste0("awk  '{FS = \";\"} ; {print NF}' ", path_leg_2017_t1," | sort -nu | tail -n 1"))

n_col <- 237  
                
nrep <- (n_col-21) / 8

col_names <- c(header_L17T1[-c(22:29)], paste0(rep(c("no_panneau", "sexe", "nom", "prenom", "nuance", "voix", "voix_ins", "voix_exp"), nrep), "_", rep(seq(1:nrep), each = 8)))

col_types_int <- vector("list", nrep + 5)
col_types_int <- map(col_types_int, ~ col_integer())
names(col_types_int) <- c("Inscrits", "Abstentions", "Votants", "Blancs", "Nuls", paste0("voix_", 1:nrep))

colClassesInt <- vector("list", nrep + 5)
colClassesInt <- map(colClassesInt, ~ "integer")
names(colClassesInt) <- c("Inscrits", "Abstentions", "Votants", "Blancs", "Nuls", paste0("voix_", 1:nrep))

col_types_char <- vector("list", n_col - length(col_types_int)) 
col_types_char <- map(col_types_char, ~ col_character())
names(col_types_char) <- col_names[-which(col_names %in% names(col_types_int))]

colClassesChar <- vector("list", n_col - length(col_types_int)) 
colClassesChar <- map(colClassesChar, ~ "character")
names(colClassesChar) <- col_names[-which(col_names %in% names(col_types_int))]

# sed -i '1c\Code du département;Libellé du département;Code de la circonscription;Libellé de la circonscription;Code de la commune;Libellé de la commune;Code du b.vote;Inscrits;Abstentions;% Abs/Ins;Votants;% Vot/Ins;Blancs;% Blancs/Ins;% Blancs/Vot;Nuls;% Nuls/Ins;% Nuls/Vot;Exprimés;% Exp/Ins;% Exp/Vot;no_panneau_1;sexe_1;nom_1;prenom_1;nuance_1;voix_1;voix_ins_1;voix_exp_1;no_panneau_2;sexe_2;nom_2;prenom_2;nuance_2;voix_2;voix_ins_2;voix_exp_2;no_panneau_3;sexe_3;nom_3;prenom_3;nuance_3;voix_3;voix_ins_3;voix_exp_3;no_panneau_4;sexe_4;nom_4;prenom_4;nuance_4;voix_4;voix_ins_4;voix_exp_4;no_panneau_5;sexe_5;nom_5;prenom_5;nuance_5;voix_5;voix_ins_5;voix_exp_5;no_panneau_6;sexe_6;nom_6;prenom_6;nuance_6;voix_6;voix_ins_6;voix_exp_6;no_panneau_7;sexe_7;nom_7;prenom_7;nuance_7;voix_7;voix_ins_7;voix_exp_7;no_panneau_8;sexe_8;nom_8;prenom_8;nuance_8;voix_8;voix_ins_8;voix_exp_8;no_panneau_9;sexe_9;nom_9;prenom_9;nuance_9;voix_9;voix_ins_9;voix_exp_9;no_panneau_10;sexe_10;nom_10;prenom_10;nuance_10;voix_10;voix_ins_10;voix_exp_10;no_panneau_11;sexe_11;nom_11;prenom_11;nuance_11;voix_11;voix_ins_11;voix_exp_11;no_panneau_12;sexe_12;nom_12;prenom_12;nuance_12;voix_12;voix_ins_12;voix_exp_12;no_panneau_13;sexe_13;nom_13;prenom_13;nuance_13;voix_13;voix_ins_13;voix_exp_13;no_panneau_14;sexe_14;nom_14;prenom_14;nuance_14;voix_14;voix_ins_14;voix_exp_14;no_panneau_15;sexe_15;nom_15;prenom_15;nuance_15;voix_15;voix_ins_15;voix_exp_15;no_panneau_16;sexe_16;nom_16;prenom_16;nuance_16;voix_16;voix_ins_16;voix_exp_16;no_panneau_17;sexe_17;nom_17;prenom_17;nuance_17;voix_17;voix_ins_17;voix_exp_17;no_panneau_18;sexe_18;nom_18;prenom_18;nuance_18;voix_18;voix_ins_18;voix_exp_18;no_panneau_19;sexe_19;nom_19;prenom_19;nuance_19;voix_19;voix_ins_19;voix_exp_19;no_panneau_20;sexe_20;nom_20;prenom_20;nuance_20;voix_20;voix_ins_20;voix_exp_20;no_panneau_21;sexe_21;nom_21;prenom_21;nuance_21;voix_21;voix_ins_21;voix_exp_21;no_panneau_22;sexe_22;nom_22;prenom_22;nuance_22;voix_22;voix_ins_22;voix_exp_22;no_panneau_23;sexe_23;nom_23;prenom_23;nuance_23;voix_23;voix_ins_23;voix_exp_23;no_panneau_24;sexe_24;nom_24;prenom_24;nuance_24;voix_24;voix_ins_24;voix_exp_24;no_panneau_25;sexe_25;nom_25;prenom_25;nuance_25;voix_25;voix_ins_25;voix_exp_25;no_panneau_26;sexe_26;nom_26;prenom_26;nuance_26;voix_26;voix_ins_26;voix_exp_26;no_panneau_27;sexe_27;nom_27;prenom_27;nuance_27;voix_27;voix_ins_27;voix_exp_27' legislatives_2017_T1_bv.csv



legislatives_2017_t1_bv <- read_csv2(here("data", "legislatives_2017_T1_bv.csv"), locale = locale(encoding = "ISO-8859-1"), col_types = c(col_types_char, col_types_int))
names(legislatives_2017_t1_bv) <- col_names

leg_2017_R1_BV_cleaned <- LireMinInterieur::lire(legislatives_2017_t1_bv, keep = names(legislatives_2017_t1_bv)[c(1,3,5,7:9,11,13,16,19)], col = seq(26, n_col, 8), gap = 1)

leg_2017_R1_BV_cleaned <- leg_2017_R1_BV_cleaned %>% 
  mutate(CodeDepartement = str_pad(string = `Code du département`, width = 2, side = "left", pad = "0")) %>% # has to be in a format like "02"
  mutate(NumeroCirco = str_pad(`Code de la circonscription`, 2, "left", "0")) %>%
  mutate(CodeCirco = paste0(CodeDepartement, NumeroCirco)) %>% 
  mutate(CodeCommune = str_pad(string = `Code de la commune`, width = 3, side = "left", pad = "0")) %>% 
  mutate(CodeInsee = paste0(CodeDepartement, CodeCommune)) %>%  # unique commune ID
  # computing missing values
  mutate(NumeroBV = str_pad(`Code du b.vote`, width = "4", side = "left", pad = "0")) %>% 
  mutate(CodeBV = paste0(CodeInsee, NumeroBV)) %>% 
  mutate(Votants = Inscrits - Abstentions) %>% 
  mutate(Votants_ins = Votants / Inscrits * 100) %>% 
  mutate(Abstentions_ins = Abstentions / Inscrits * 100) %>% 
  mutate(Blancs_ins = Blancs/ Inscrits * 100) %>% 
  mutate(Blancs_vot = Blancs / Votants * 100) %>% 
  mutate(Nuls_ins = Nuls / Inscrits * 100) %>% 
  mutate(Nuls_vot = Nuls / Votants * 100) %>% 
  mutate(Exprimés_ins = Exprimés / Inscrits * 100) %>% 
  mutate (Exprimés_vot = Exprimés / Votants * 100) %>% 
  # specify integers %>% 
  mutate_at(vars(Inscrits, Abstentions, Votants, Blancs, Nuls, Exprimés, EXG:EXD), as.integer) %>% 
  as_tibble()

leg_2017_R1_BV_cleaned %>% write_excel_csv(here("data", "leg_2017_t1_bv.csv"))

# leg_2017_R1_BV_cleaned <- read_csv(here("data", "leg_2017_t1_bv.csv"))

# présidentielle 2022 T1

# download.file("https://www.data.gouv.fr/fr/datasets/r/79b5cac4-4957-486b-bbda-322d80868224", destfile = here("data", "pre_2022_t1_bv.csv"))
header_P22T1 <- names(read_csv(here("data", "pre_2022_t1_bv.csv"), locale = locale(encoding = "UTF-8"), n_max = 1))
n_col <- ncol(read_csv(here("data", "pre_2022_t1_bv.csv"), locale = locale(encoding = "UTF-8"), skip = 1, col_names =FALSE))
nrep <- (n_col-21) / 7
presidentielle_2022_t1_bv <- read_csv(here("data", "pre_2022_t1_bv.csv"), locale = locale(encoding = "UTF-8"), skip = 1, col_names = c(header_P17T2[-c(22:28)], paste0(rep(c("no_panneau", "sexe", "nom", "prenom", "voix", "voix_ins", "voix_exp"), nrep), "_", rep(seq(1:nrep), each = 7))))

presidentielle_2022_t1_bv_cleaned <- LireMinInterieur::lire(presidentielle_2022_t1_bv, keep = names(presidentielle_2022_t1_bv)[c(1,3,5,7:9,11,13,16,19)], col = seq(24, n_col, 7), gap = 2)

presidentielle_2022_t1_bv_cleaned <- presidentielle_2022_t1_bv_cleaned %>% 
  mutate(CodeDepartement = str_pad(string = `Code du département`, width = 2, side = "left", pad = "0")) %>% # has to be in a format like "02"
  mutate(NumeroCirco = str_pad(`Code de la circonscription`, 2, "left", "0")) %>%
  mutate(CodeCirco = paste0(CodeDepartement, NumeroCirco)) %>% 
  mutate(CodeCommune = str_pad(string = `Code de la commune`, width = 3, side = "left", pad = "0")) %>% 
  mutate(CodeInsee = paste0(CodeDepartement, CodeCommune)) %>%  # unique commune ID
  # computing missing values
  mutate(NumeroBV = str_pad(`Code du b.vote`, width = "4", side = "left", pad = "0")) %>% 
  mutate(CodeBV = paste0(CodeInsee, NumeroBV)) %>% 
  mutate(Votants = Inscrits - Abstentions) %>% 
  mutate(Votants_ins = Votants / Inscrits * 100) %>% 
  mutate(Abstentions_ins = Abstentions / Inscrits * 100) %>% 
  mutate(Blancs_ins = Blancs/ Inscrits * 100) %>% 
  mutate(Blancs_vot = Blancs / Votants * 100) %>% 
  mutate(Nuls_ins = Nuls / Inscrits * 100) %>% 
  mutate(Nuls_vot = Nuls / Votants * 100) %>% 
  mutate(Exprimés_ins = Exprimés / Inscrits * 100) %>% 
  mutate (Exprimés_vot = Exprimés / Votants * 100) %>% 
  # specify integers %>% 
  mutate(across(c(Inscrits, Abstentions, Votants, Blancs, Nuls, Exprimés, ARTHAUD:`DUPONT-AIGNAN`), ~ as.integer(.))) %>% 
  as_tibble()

presidentielle_2022_t1_bv_cleaned %>% write_excel_csv(here("data", "pre_2022_t1_bv.csv"))
# presidentielle_2022_t1_bv_cleaned <- read_csv(here("data", "pre_2022_t1_bv.csv"))

# présidentielle 2022 T2

download.file("https://www.data.gouv.fr/fr/datasets/r/4dfd05a9-094e-4043-8a19-43b6b6bbe086", destfile = here("data", "pre_2022_t2_bv.csv"))
header_P22T2 <- names(read_csv2(here("data", "pre_2022_t2_bv.csv"), locale = locale(encoding = "ISO-8859-1"), n_max = 1))
n_col <- ncol(read_csv2(here("data", "pre_2022_t2_bv.csv"), locale = locale(encoding = "ISO-8859-1"), skip = 1, col_names =FALSE))
nrep <- (n_col-21) / 7
presidentielle_2022_t2_bv <- read_csv2(here("data", "pre_2022_t2_bv.csv"), locale = locale(encoding = "ISO-8859-1"), skip = 1, col_names = c(header_P22T2[-c(22:28)], paste0(rep(c("no_panneau", "sexe", "nom", "prenom", "voix", "voix_ins", "voix_exp"), nrep), "_", rep(seq(1:nrep), each = 7))))

presidentielle_2022_t2_bv_cleaned <- LireMinInterieur::lire(presidentielle_2022_t2_bv, keep = names(presidentielle_2022_t2_bv)[c(1,3,5,7:9,11,13,16,19)], col = seq(24, n_col, 7), gap = 2)

presidentielle_2022_t2_bv_cleaned <- presidentielle_2022_t2_bv_cleaned %>% 
  mutate(CodeDepartement = str_pad(string = `Code du département`, width = 2, side = "left", pad = "0")) %>% # has to be in a format like "02"
  mutate(NumeroCirco = str_pad(`Code de la circonscription`, 2, "left", "0")) %>%
  mutate(CodeCirco = paste0(CodeDepartement, NumeroCirco)) %>% 
  mutate(CodeCommune = str_pad(string = `Code de la commune`, width = 3, side = "left", pad = "0")) %>% 
  mutate(CodeInsee = paste0(CodeDepartement, CodeCommune)) %>%  # unique commune ID
  # computing missing values
  mutate(NumeroBV = str_pad(`Code du b.vote`, width = "4", side = "left", pad = "0")) %>% 
  mutate(CodeBV = paste0(CodeInsee, NumeroBV)) %>% 
  mutate(Votants = Inscrits - Abstentions) %>% 
  mutate(Votants_ins = Votants / Inscrits * 100) %>% 
  mutate(Abstentions_ins = Abstentions / Inscrits * 100) %>% 
  mutate(Blancs_ins = Blancs/ Inscrits * 100) %>% 
  mutate(Blancs_vot = Blancs / Votants * 100) %>% 
  mutate(Nuls_ins = Nuls / Inscrits * 100) %>% 
  mutate(Nuls_vot = Nuls / Votants * 100) %>% 
  mutate(Exprimés_ins = Exprimés / Inscrits * 100) %>% 
  mutate (Exprimés_vot = Exprimés / Votants * 100) %>% 
  # specify integers %>% 
  mutate(across(c(Inscrits, Abstentions, Votants, Blancs, Nuls, Exprimés, MACRON, `LE PEN`), ~ as.integer(.))) %>% 
  as_tibble()

presidentielle_2022_t2_bv_cleaned %>% write_excel_csv(here("data", "pre_2022_t2_bv.csv"))
# presidentielle_2022_t2_bv_cleaned <- read_csv(here("data", "pre_2022_t2_bv.csv"))

# législatives 2022 T1

download.file("https://www.data.gouv.fr/fr/datasets/r/a1f73b85-8194-44f4-a2b7-c343edb47d32", destfile = here("data", "legislatives_2022_T1_bv.csv"))

header_L22T1 <- names(read_csv2(here("data", "legislatives_2022_T1_bv.csv"), locale = locale(encoding = "ISO-8859-1"), n_max = 1))
n_col <- ncol(read_csv2(here("data", "legislatives_2022_T1_bv.csv"), locale = locale(encoding = "ISO-8859-1"), skip = 1, col_names =FALSE))
nrep <- (n_col-21) / 8
legislatives_2022_t1_bv <- read_csv2(here("data", "legislatives_2022_T1_bv.csv"), locale = locale(encoding = "ISO-8859-1"), skip = 1, col_names = c(header_L22T1[-c(22:29)], paste0(rep(c("no_panneau", "sexe", "nom", "prenom", "nuance", "voix", "voix_ins", "voix_exp"), nrep), "_", rep(seq(1:nrep), each = 8))))

leg_2022_R1_BV_cleaned <- LireMinInterieur::lire(legislatives_2022_t1_bv, keep = names(legislatives_2022_t1_bv)[c(1,3,5,7:9,11,13,16,19)], col = seq(26, n_col, 8), gap = 1)

leg_2022_R1_BV_cleaned <- leg_2022_R1_BV_cleaned %>% 
  mutate(CodeDepartement = str_pad(string = `Code du département`, width = 2, side = "left", pad = "0")) %>% # has to be in a format like "02"
  mutate(NumeroCirco = str_pad(`Code de la circonscription`, 2, "left", "0")) %>%
  mutate(CodeCirco = paste0(CodeDepartement, NumeroCirco)) %>% 
  mutate(CodeCommune = str_pad(string = `Code de la commune`, width = 3, side = "left", pad = "0")) %>% 
  mutate(CodeInsee = paste0(CodeDepartement, CodeCommune)) %>%  # unique commune ID
  # computing missing values
  mutate(NumeroBV = str_pad(`Code du b.vote`, width = "4", side = "left", pad = "0")) %>% 
  mutate(CodeBV = paste0(CodeInsee, NumeroBV)) %>% 
  mutate(Votants = Inscrits - Abstentions) %>% 
  mutate(Votants_ins = Votants / Inscrits * 100) %>% 
  mutate(Abstentions_ins = Abstentions / Inscrits * 100) %>% 
  mutate(Blancs_ins = Blancs/ Inscrits * 100) %>% 
  mutate(Blancs_vot = Blancs / Votants * 100) %>% 
  mutate(Nuls_ins = Nuls / Inscrits * 100) %>% 
  mutate(Nuls_vot = Nuls / Votants * 100) %>% 
  mutate(Exprimés_ins = Exprimés / Inscrits * 100) %>% 
  mutate (Exprimés_vot = Exprimés / Votants * 100) %>% 
  # specify integers %>% 
  mutate_at(vars(Inscrits, Abstentions, Votants, Blancs, Nuls, Exprimés, DXG:DXD), as.integer) %>% 
  as_tibble()

leg_2022_R1_BV_cleaned %>% write_excel_csv(here("data", "leg_2022_t1_bv.csv"))

# leg_2022_R1_BV_cleaned <- read_csv(here("data", "leg_2017_t1_bv.csv"))



```


```{r repartition_qpv}

# on peut maintenant calculer le vote des QPV

# il faut d'abord matcher les bv avec les résultats 2017

bv_grandlyon_p2017_t1_res <- bv_2017 %>% 
  mutate(bureau_vote_id = str_replace(bureau_vote_id, "6938[1-9]", "69123")) %>% 
  left_join(presidentielle_2017_t1_bv, by = join_by(bureau_vote_id == CodeBV)) %>% 
  filter(!is.na(Inscrits))
st_write(bv_grandlyon_p2017_t1_res, here("output_data", "bv_grandlyon_p2017_t1_res.gpkg"), append = FALSE)


bv_grandlyon_p2017_t2_res <- bv_2017 %>% 
  mutate(bureau_vote_id = str_replace(bureau_vote_id, "6938[1-9]", "69123")) %>% 
  left_join(presidentielle_2017_t2_bv, by = join_by(bureau_vote_id == CodeBV)) %>% 
  filter(!is.na(Inscrits))
st_write(bv_grandlyon_p2017_t2_res, here("output_data", "bv_grandlyon_p2017_t2_res.gpkg"))

bv_grandlyon_l2017_t1_res <- bv_communes_2017 %>% 
  mutate(bureau_vote_id = str_replace(bureau_vote_id, "6938[1-9]", "69123")) %>% 
  left_join(leg_2017_R1_BV_cleaned, by = join_by(bureau_vote_id == CodeBV)) %>% 
  filter(!is.na(Inscrits))
st_write(bv_grandlyon_l2017_t1_res, here("output_data", "bv_grandlyon_l2017_t1_res.gpkg"))

# puis les résultats 2022

bv_grandlyon_p2022_t1_res <- bv_communes_2022 %>% 
  mutate(bureau_vote_id = str_replace(bureau_vote_id, "6938[1-9]", "69123")) %>% 
  left_join(presidentielle_2022_t1_bv_cleaned, by = join_by(bureau_vote_id == CodeBV)) %>% 
  filter(!is.na(Inscrits))
st_write(bv_grandlyon_p2022_t1_res, here("output_data", "bv_grandlyon_p2022_t1_res.gpkg"))

bv_grandlyon_p2022_t2_res <- bv_communes_2022 %>% 
  mutate(bureau_vote_id = str_replace(bureau_vote_id, "6938[1-9]", "69123")) %>% 
  left_join(presidentielle_2022_t2_bv_cleaned, by = join_by(bureau_vote_id == CodeBV)) %>% 
  filter(!is.na(Inscrits))
st_write(bv_grandlyon_p2022_t2_res, here("output_data", "bv_grandlyon_p2022_t2_res.gpkg"))

bv_grandlyon_l2022_t1_res <- bv_communes_2022 %>% 
  mutate(bureau_vote_id = str_replace(bureau_vote_id, "6938[1-9]", "69123")) %>% 
  left_join(leg_2022_R1_BV_cleaned, by = join_by(bureau_vote_id == CodeBV)) %>% 
  filter(!is.na(Inscrits))
st_write(bv_grandlyon_l2022_t1_res, here("output_data", "bv_grandlyon_l2022_t1_res.gpkg"))


# qpv69 <- qpv %>% 
#   filter(str_detect(CODE_QP, "QP069"))

# l'une des géométries est invalide. Il a fallu la modifier manuellement avec QGIS.

# rm(qpv69)
qpv69 <- st_read(here("data", "qpv69.gpkg"))
qpv_gd_lyon <- qpv69 %>% slice(which(map_lgl(qpv69 %>% st_intersects(communes_gd_lyon_shp), ~ !is_empty(.))))


# puis procéder à la répartition

# P2017T1

qpv69_pres_17_t1 <- tidycensus::interpolate_pw(from = bv_grandlyon_p2017_t1_res %>% select(- contains("_ins"), -contains("_exp"), -contains("_vot")), to = qpv_gd_lyon, to_id = "CODE_QP", extensive = TRUE, weights = poids_2017, weight_column = "n")
st_write(qpv69_pres_17_t1, here("output_data", "qpv69_pres_17_t1.gpkg"), append = FALSE)


# P2017T2

qpv69_pres_17_t2 <- tidycensus::interpolate_pw(from = bv_grandlyon_p2017_t2_res, to = qpv_gd_lyon, to_id = "CODE_QP", extensive = TRUE, weights = poids_2017, weight_column = "n")
st_write(qpv69_pres_17_t2, here("output_data", "qpv69_pres_17_t2.gpkg"), append = FALSE)

# L2017T1

qpv69_leg_17_t1 <- tidycensus::interpolate_pw(from = bv_grandlyon_l2017_t1_res %>% select(-contains(".ins"), -contains("_ins"),  -contains(".exp"), -contains("_vot"), -contains("NbCand")), to = qpv_gd_lyon, to_id = "CODE_QP", extensive = TRUE, weights = poids_2017, weight_column = "n")
st_write(qpv69_leg_17_t1, here("output_data", "qpv69_leg_17_t1.gpkg"))

# P2022T1

qpv69_pre_22_t1 <- tidycensus::interpolate_pw(from = bv_grandlyon_p2022_t1_res %>% select(-contains(".ins"), -contains("_ins"),  -contains(".exp"), -contains("_vot"), -contains("NbCand")), to = qpv_gd_lyon, to_id = "CODE_QP", extensive = TRUE, weights = poids_2022, weight_column = "n")
st_write(qpv69_pre_22_t1, here("output_data", "qpv69_pre_22_t1.gpkg"))

# P2022T2

qpv69_pre_22_t2 <- tidycensus::interpolate_pw(from = bv_grandlyon_p2022_t2_res %>% select(-contains(".ins"), -contains("_ins"),  -contains(".exp"), -contains("_vot"), -contains("NbCand")), to = qpv_gd_lyon, to_id = "CODE_QP", extensive = TRUE, weights = poids_2022, weight_column = "n")
st_write(qpv69_pre_22_t2, here("output_data", "qpv69_pre_22_t2.gpkg"))

```

